name: t21-tue-simpeg

channels:
  - conda-forge
  - defaults

dependencies:
  - python>=3.6
  - numpy
  - scipy
  - matplotlib
  - jupyter
  - ipywidgets>=0.6.0
  - mkl
  - simpeg
  - pyvista
  - dask 
  - pip:
    - git+https://github.com/geoscixyz/geosci-labs.git
